name: build-push-container

on:
  push:
    tags:
      - 'v*'

jobs:
  release-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_ORG: ${{ github.actor }}
      DOCKER_TITEL: AdGuard Home + Unbound
      DOCKER_DESC: AdGuard Home + Unbound in 1 Container
      DOCKER_PACKAGE: adguardhome
      DOCKER_SRC: https://github.com/${{ github.repository }}
      DOCKER_LATEST: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3           

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD2 }}

      - name: Get Meta
        id: meta
        run: |
          echo REPO=$(echo ${{ github.actor }} | awk '{print tolower($0)}') >> $GITHUB_OUTPUT
          #echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_NAME=$(echo ${{ env.DOCKER_PACKAGE }}) >> $GITHUB_OUTPUT
          #echo VERSION=$(grep 'ENV ADGUARDHOME_VERSION=' Dockerfile | sed 's/.*ENV ADGUARDHOME_VERSION=//;s/"//g') >> $GITHUB_OUTPUT
          echo VERSION=$(echo ${GITHUB_REF#refs/tags/}) >> $GITHUB_OUTPUT
          echo DATE=$(date) >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            ADGUARDHOME_VERSION=${{ steps.meta.outputs.VERSION }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6                       
          push: true
          tags: |
            ${{ steps.meta.outputs.REPO }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.VERSION }}
            ${{ steps.meta.outputs.REPO }}/${{ steps.meta.outputs.REPO_NAME }}:${{ env.DOCKER_LATEST }}
            ghcr.io/${{ steps.meta.outputs.REPO }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.VERSION }}
            ghcr.io/${{ steps.meta.outputs.REPO }}/${{ steps.meta.outputs.REPO_NAME }}:${{ env.DOCKER_LATEST }}
          labels: |
            org.opencontainers.image.authors=${{ github.actor }}
            org.opencontainers.image.url=${{ env.DOCKER_SRC }}
            org.opencontainers.image.source=${{ env.DOCKER_SRC }}
            org.opencontainers.image.title=${{ env.DOCKER_TITEL }}
            org.opencontainers.image.description=${{ env.DOCKER_DESC }}
            org.opencontainers.image.created=${{ steps.meta.outputs.DATE }}
            org.opencontainers.image.version=${{ steps.meta.outputs.VERSION }}
          provenance: false
          outputs: |
            type=image,name=target,annotation-index.org.opencontainers.image.authors=${{ github.actor }},annotation-index.org.opencontainers.image.title=${{ env.DOCKER_TITEL }},annotation-index.org.opencontainers.image.description=${{ env.DOCKER_DESC }},annotation-index.org.opencontainers.image.url=${{ env.DOCKER_SRC }},annotation-index.org.opencontainers.image.source=${{ env.DOCKER_SRC }},annotation-index.org.opencontainers.image.created=${{ steps.meta.outputs.DATE }},annotation-index.org.opencontainers.image.version=${{ steps.meta.outputs.VERSION }},annotation-manifest.org.opencontainers.image.authors=${{ github.actor }},annotation-manifest.org.opencontainers.image.title=${{ env.DOCKER_TITEL }},annotation-manifest.org.opencontainers.image.description=${{ env.DOCKER_DESC }},annotation-manifest.org.opencontainers.image.url=${{ env.DOCKER_SRC }},annotation-manifest.org.opencontainers.image.source=${{ env.DOCKER_SRC }},annotation-manifest.org.opencontainers.image.created=${{ steps.meta.outputs.DATE }},annotation-manifest.org.opencontainers.image.version=${{ steps.meta.outputs.VERSION }}
        env:
          DOCKER_BUILD_SUMMARY: true
